FROM httpd:2-alpine

# ----------------------------------------
# Install / Update Packages
# ----------------------------------------

RUN apk update \
    && \
    apk add --no-cache \
        nano \
        shadow

# ----------------------------------------
# Update user
# ----------------------------------------

ARG USER_ID=1000
ARG GROUP_ID=1000

# Make www-data uid and gid match the host
# This allows the host to add/edit/remove files
RUN usermod -u $USER_ID www-data \
    && \
    groupmod -g $GROUP_ID www-data

# ----------------------------------------
# Configure
# ----------------------------------------

# Copy httpd-custom.conf
COPY ./docker/apache/httpd-custom.conf /usr/local/apache2/conf/httpd-custom.conf

# Include the httpd-custom.conf in httpd.conf
RUN echo "Include /usr/local/apache2/conf/httpd-custom.conf" >> /usr/local/apache2/conf/httpd.conf