FROM php:7-fpm-alpine

# ----------------------------------------
# Install / Update Packages
# ----------------------------------------

# Add docker-php-extension-installer
# See https://github.com/mlocati/docker-php-extension-installer for more information
ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/
RUN chmod uga+x /usr/local/bin/install-php-extensions && \
    sync

# Install packages
RUN apk update \
    && \
    apk add --no-cache \
        mariadb-client \
        mariadb-connector-c \
        nano \
        shadow \
    && \
    install-php-extensions \
        imagick \
        intl \
        opcache \
        pdo_mysql \
        redis \
        zip

# Install Composer and Plugins
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer \
    && \
    composer global require \
        hirak/prestissimo

# ----------------------------------------
# Update user
# ----------------------------------------

ARG USER_ID=1000
ARG GROUP_ID=1000

# Make www-data uid and gid match the host
# This allows the host to add/edit/remove files
RUN usermod -u $USER_ID www-data \
    && \
    groupmod -g $GROUP_ID www-data

# ----------------------------------------
# Configure PHP
# ----------------------------------------

# Use the default production configuration
RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini

# Copy php-custom.ini
COPY ./docker/php/php-custom.ini $PHP_INI_DIR/conf.d/php-custom.ini

# ----------------------------------------
# Configure Craft CMS
# ----------------------------------------

WORKDIR /var/www/html

# Copy Craft CMS composer files
COPY --chown=www-data:www-data ./src ./

# Install vendor files and update permissions
RUN composer install --no-scripts --optimize-autoloader --no-interaction \
    && \
    chown -R www-data:www-data .
    
# Start php-fpm
CMD php-fpm