version: '3'

services:
    web:
        build:
            context: .
            dockerfile: ./docker/apache/dockerfile
        networks:
            - frontend
        ports:
            - 8000:80
        volumes:
            - ./container/web:/var/www/html/web:cached
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: ./docker/php/dockerfile
        networks:
            - frontend
            - backend
        volumes:
            - ./container:/var/www/html
            - /var/www/html/vendor
        env_file:
            - ./.env
        depends_on:
            - database
            - redis

    database:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - backend
        volumes:
            - db-data:/var/lib/mysql
        env_file:
            - ./.env

    redis:
        image: redis:6-alpine
        networks:
            - backend

volumes:
    db-data:

networks:
    frontend:
    backend:
