version: '3'

services:
    web:
        container_name: craft_web
        build:
            context: .
            dockerfile: ./docker-config/apache/dockerfile
        networks:
            - frontend
        ports:
            - 8000:80
        volumes:
            - cpresources:/var/www/html/web/cpresources
            - ./cms/web:/var/www/html/web:cached
        
    php:
        container_name: craft_php
        build:
            context: .
            dockerfile: ./docker-config/php/dockerfile
        networks:
            - frontend
            - backend
        volumes:
            - storage:/var/www/html/storage/
            - vendor:/var/www/html/vendor/
            - cpresources:/var/www/html/web/cpresources/
            - ./cms:/var/www/html/:cached
            - ./cms/storage/logs:/var/www/html/storage/logs/:delegated
            - ./cms/storage/rebrand:/var/www/html/storage/rebrand/:delegated
        env_file:
            - ./docker-config/.env
            
    database:
        container_name: craft_db
        build:
            context: .
            dockerfile: ./docker-config/mysql/dockerfile
        networks:
            - backend
        volumes:
            - db-data:/var/lib/mysql
        env_file:
            - ./docker-config/.env

volumes:
    storage:
    vendor:
    cpresources:
    db-data:

networks:
    frontend:
    backend:
