version: '3'

services:
    # Web Server
    server:
        container_name: craft_web
        build:
            context: .
            dockerfile: ./docker-config/apache/dockerfile
        networks:
            - frontend
            - backend
        ports:
            - 80:80
            - 443:443
        volumes:
            - cpresources:/var/www/html/web/cpresources
            - ./cms/web:/var/www/html/web:cached
        depends_on:
            - php
            - database
        
    # PHP
    php:
        container_name: craft_php
        build:
            context: .
            dockerfile: ./docker-config/php/dockerfile
        networks:
            - backend
        ports:
            - 9000:9000
        volumes:
            - storage:/var/www/html/storage/
            - vendor:/var/www/html/vendor/
            - cpresources:/var/www/html/web/cpresources/
            - ./cms:/var/www/html/:cached
            - ./cms/storage/logs:/var/www/html/storage/logs/:delegated
            - ./cms/storage/rebrand:/var/www/html/storage/rebrand/:delegated
        env_file:
            - ./docker-config/.env
        depends_on: 
            - database
            
    # MySQL
    database:
        container_name: craft_db
        build:
            context: .
            dockerfile: ./docker-config/mysql/dockerfile
        networks:
            - backend
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        env_file:
            - ./docker-config/.env

volumes:
    storage:
    vendor:
    cpresources:
    db-data:

networks:
    frontend:
    backend:
