version: '3'

services:
    web:
        build:
            context: .
            dockerfile: ./docker-config/apache/dockerfile
        networks:
            - frontend
        ports:
            - 8000:80
        volumes:
            - cpresources:/var/www/html/web/cpresources
            - ./cms/web:/var/www/html/web:cached
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: ./docker-config/php/dockerfile
        networks:
            - frontend
            - backend
        volumes:
            - cpresources:/var/www/html/web/cpresources
            - storage:/var/www/html/storage
            - vendor:/var/www/html/vendor
            - ./cms:/var/www/html:cached
            - ./cms/storage/logs:/var/www/html/storage/logs:delegated
            - ./cms/storage/rebrand:/var/www/html/storage/rebrand:delegated
        env_file:
            - ./docker-config/.env
        depends_on:
            - database
            - redis

    database:
        build:
            context: .
            dockerfile: ./docker-config/mysql/dockerfile
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - backend
        volumes:
            - db-data:/var/lib/mysql
        env_file:
            - ./docker-config/.env

    redis:
        networks:
            - backend
        build:
            context: .
            dockerfile: ./docker-config/redis/dockerfile

volumes:
    storage:
    vendor:
    cpresources:
    db-data:

networks:
    frontend:
    backend:
