version: '3.7'

services:
    # Apache
    server:
        container_name: craft_web
        build:
            context: .
            dockerfile: ./docker-config/apache/dockerfile
        ports:
            - 8000:80
        volumes:
            - cpresources:/var/www/project/web/cpresources
            - storage:/var/www/project/storage
            - ./cms:/var/www/project:cached
            - ./cms/vendor:/var/www/project/vendor:delegated
            - ./cms/storage/logs:/var/www/project/storage/logs:delegated
            
    # MySQL
    database:
        container_name: craft_db
        build:
            context: .
            dockerfile: ./docker-config/mysql/dockerfile
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: project
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306

volumes:
    db-data:
    cpresources:
    storage:
