FROM httpd:2.4-alpine

# ----------------------------------------
# Install / Update Packages
# ----------------------------------------

RUN apk update; \
    apk upgrade;

# ----------------------------------------
# Configure
# ----------------------------------------

# Copy apache vhost file to proxy php requests to php-fpm container
COPY ./docker-config/apache/custom.conf /usr/local/apache2/conf/custom.conf

# Include the custom.conf in httpd.conf
RUN echo "Include /usr/local/apache2/conf/custom.conf" >> /usr/local/apache2/conf/httpd.conf