FROM httpd:2.4

# ----------------------------------------
# Install / Update Packages
# ----------------------------------------

# General Update
RUN apt-get update && apt-get upgrade --yes --quiet

# Install Packages
RUN apt-get install --yes --quiet \
    nano

# ----------------------------------------
# Configure
# ----------------------------------------

# Make a backup of the default httpd config
RUN cp /usr/local/apache2/conf/httpd.conf /usr/local/apache2/conf/httpd.conf.bak

# Copy over the custom httpd config
COPY  ./docker-config/apache/custom.conf /usr/local/apache2/conf/httpd.conf

# ----------------------------------------
# Command
# ----------------------------------------

CMD apachectl -D FOREGROUND