FROM php:7-fpm-alpine

# ----------------------------------------
# Install / Update Packages
# ----------------------------------------

# Add docker-php-extension-installer
# See https://github.com/mlocati/docker-php-extension-installer for more information
ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/
RUN chmod uga+x /usr/local/bin/install-php-extensions && \
    sync

# Add packages
RUN apk update && \
    apk upgrade && \
    apk add nano && \
    install-php-extensions imagick && \
    install-php-extensions pdo_mysql && \
    install-php-extensions intl && \
    install-php-extensions zip

# Install Composer and Plugins
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer && \
    composer global require hirak/prestissimo && \
    composer global require repman-io/composer-plugin

# ----------------------------------------
# Configure
# ----------------------------------------

# Use the default production configuration
RUN cp $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini

# Copy php-custom.ini
COPY ./docker-config/php/php-custom.ini $PHP_INI_DIR/conf.d/php-custom.ini

# ----------------------------------------
# Setup Craft CMS
# ----------------------------------------

WORKDIR /var/www/html

# Copy over the directories/files
COPY ./cms/ /var/www/html/

# If `composer.lock` OR `/vendor` is missing, 
# - Do a `composer install` without running any Composer scripts
# - Force permissions
# Start php-fpm
CMD if [ ! -f "./composer.lock" ] || [ ! -d ./vendor -o ! "$(ls -A ./vendor)" ]; then \
        composer install --no-scripts --optimize-autoloader --no-interaction; \
    fi \
    && \
    php-fpm
