currLabel: Assets
customIcon: null
enabled: true
handle: assets
icon: assets
layout: a479f0d2-12f4-4887-be99-24023a8e5a1f
newWindow: false
order: 2
prevLabel: Assets
prevUrl: assets
type: ''
url: assets
