currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: section
layout: a479f0d2-12f4-4887-be99-24023a8e5a1f
newWindow: false
order: 1
prevLabel: Entries
prevUrl: entries
type: ''
url: entries
