currLabel: GraphQL
customIcon: null
enabled: true
handle: graphql
icon: '@app/icons/graphql.svg'
layout: a479f0d2-12f4-4887-be99-24023a8e5a1f
newWindow: false
order: 4
prevLabel: GraphQL
prevUrl: graphql
type: ''
url: graphql
